"""add artist_name

Revision ID: 3671fe7c4fd5
Revises: a0130fd5e4da
Create Date: 2025-03-16 20:42:10.160443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3671fe7c4fd5'
down_revision = 'a0130fd5e4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('artist_name')

    # ### end Alembic commands ###
